apiVersion: v1
kind: Pod
metadata:
  name: progress-service
  labels:
    app: progress-service
spec:
  containers:
  - name: progress-app
    image: progress-service:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 8000
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
---
apiVersion: v1
kind: Pod
metadata:
  name: todo-service
  labels:
    app: todo-service
spec:
  containers:
  - name: todo-app
    image: todo-service:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 8000
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    - name: PROGRESS_API_URL
      value: "http://progress-service:8000"
